"""empty message

Revision ID: 6f8241f9cdba
Revises: b8e2a929f5de
Create Date: 2020-05-17 20:55:33.299241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6f8241f9cdba'
down_revision = 'b8e2a929f5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    credit_types = postgresql.ENUM('promotional', 'regular', name='credit_types')
    credit_types.create(op.get_bind())

    op.add_column('credit', sa.Column('credit_type', sa.Enum('PROMOTIONAL', 'REGULAR', name='credit_types'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'credit_type')

    # ### end Alembic commands ###

    credit_types = postgresql.ENUM('promotional', 'regular', name='credit_types')
    credit_types.drop(op.get_bind())
