"""empty message

Revision ID: b8e2a929f5de
Revises: 16fb022e00d3
Create Date: 2020-05-17 20:38:31.916360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e2a929f5de'
down_revision = '16fb022e00d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    op.add_column('credit', sa.Column('amount', sa.BigInteger(), nullable=False))
    op.add_column('credit', sa.Column('depleted', sa.Boolean(), nullable=False))
    op.add_column('credit', sa.Column('expired', sa.Boolean(), nullable=False))
    op.add_column('credit', sa.Column('expiry_date', sa.Date(), nullable=False))
    op.create_unique_constraint(None, 'credit', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'credit', type_='unique')
    op.drop_column('credit', 'expiry_date')
    op.drop_column('credit', 'expired')
    op.drop_column('credit', 'depleted')
    op.drop_column('credit', 'amount')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
